syntax on
filetype plugin indent on

let mapleader=","

set autoindent            " Always set autoindenting on
set copyindent            " Copy the previous indentation on autoindenting
set expandtab             " Use spaces instead of tabs
set hidden                " Allow buffers to be hidden
set hlsearch              " Highlight search terms
set ignorecase            " Ignore case when searching
set incsearch             " Show search matches as you type
set nobackup              " Backup files are not needed
set nowrap                " Don't wrap lines
set number relativenumber " Always show relative line numbers
set ruler                 " Show line & column number
set scrolloff=5           " Leave at least five lines below the cursor
set shiftround            " Use multiple of shiftwidth when indenting with '<' and '>'
set shiftwidth=2          " Number of spaces to use for autoindenting
set showmatch             " Set show matching parenthesis
set smartcase             " Ignore case if search pattern is all lowercase, case-sensitive otherwise
set smarttab              " Insert tabs on the start of a line according to shiftwidth, not tabstop
set tabstop=2             " A tab is 2 spaces
set visualbell            " Disable beeps

" Remember last position in file
au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal g'\"" | endif

" Word completion
set complete+=kspell

" Strongly encourage using movements
let g:hardtime_default_on = 1

" Save time on EVERY vim command
nnoremap ; :

:highlight ExtraWhitespace ctermbg=red guibg=red
:match ExtraWhitespace /\s\+$/

fun! TrimWhitespace()
  let l:save = winsaveview()
  keeppatterns %s/\s\+$//e
  call winrestview(l:save)
endfun

command! TrimWhitespace call TrimWhitespace()
noremap <Leader>w :call TrimWhitespace()

function! s:goyo_enter()
  set noshowmode
  set noshowcmd
  set wrap
  set scrolloff=999
endfunction

function! s:goyo_leave()
  set showmode
  set showcmd
  set nowrap
  set scrolloff=5
endfunction

autocmd! User GoyoEnter nested call <SID>goyo_enter()
autocmd! User GoyoLeave nested call <SID>goyo_leave()

" Use The Silver Searcher https://github.com/ggreer/the_silver_searcher
if executable('ag')
  " Use Ag over Grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif

let g:ale_linters = {'ruby': ['standardrb']}
let g:ale_fixers = {'ruby': ['standardrb']}
let g:ale_fix_on_save = 1

:autocmd Filetype ruby set sw=2
:autocmd Filetype ruby set ts=2
:autocmd Filetype ruby set expandtab

:autocmd FileType gitcommit setlocal spell
