alias ll='ls -l'
alias la='ls -la'
alias l1='ls -1'

alias webs="ruby -rwebrick -e'WEBrick::HTTPServer.new(:Port => 2999, :DocumentRoot => Dir.pwd).start'"

alias bx='bundle exec'
alias bi='bundle install -j4'
alias r='bx rake'
alias g='bx guard'
alias ts='bx thin start'
alias mm='bx middleman'
alias jj='bx jekyll serve --watch'
alias jjd='jj --drafts'
alias z='zeus'
alias zs='zeus start'
alias zz='zeus server'

alias rv='rbenv versions'

alias g-='git co -'
alias gH='git reset --hard HEAD'
alias ga='git add . && gst'
alias gamd='git commit -a --amend --no-edit'
alias gb='git branch -vv'
alias gba='git branch -avv'
alias gca='git commit -v -a'
alias gcb='git co -b'
alias gd='git diff'
alias gdh='git diff HEAD'
alias gl='git lg'
alias glp='gl -p'
alias gmt='git mergetool'
alias gp='git pull'
alias gpr='git pull --rebase'
alias gph='git push'
alias gpo='git push origin'
alias grc='git rebase --continue'
alias grm='git ls-files -d | xargs git rm; gst'
alias gsh='git show'
alias gst='git status --ignore-submodules=dirty'

alias hs='hugo server --disableLiveReload'
